FROM openjdk:8-jre-alpine
# copy application WAR (with libraries inside)
COPY target/spring-boot-rest-example*.war /bt-docker-demo-app.war
# specify default command
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=prod", "/bt-docker-demo-app.war"]
